# Generated by Django 6.0.3 on 2026-05-31 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('core', '0002_notification'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='addresses.address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.malaisiancity'),
        ),
    ]
