# Generated by Django 6.0.3 on 2026-06-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderstatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('validated', "Validée par l'administration"), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('importing', 'import in progress'), ('delivering', 'Delivering in progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
