# Generated by Django 6.0.3 on 2026-05-17 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveBigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('race_type', models.CharField(choices=[('circuit', 'Circuit'), ('drift', 'Drift'), ('rally', 'Rally'), ('drag', 'Drag Race'), ('amateur', 'Compétition amateur'), ('f1', 'Formula 1'), ('gt', 'GT Racing'), ('endurance', 'Endurance'), ('touring', 'Touring Car'), ('motogp', 'Moto GP'), ('superbike', 'Superbike'), ('offroad', 'Off Road'), ('indycar', 'IndyCar Series'), ('formuleE', 'Formule E'), ('hypercars', 'Hypercars / Prototypes')], max_length=50)),
                ('power_hp', models.PositiveBigIntegerField()),
                ('mileage', models.PositiveBigIntegerField(help_text='Mileage en km')),
                ('conditions', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('needs_work', 'Needs Work')], max_length=50)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('sequential', 'Sequential')], max_length=50)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='cars/main/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_reserved', models.BooleanField(default=False)),
                ('is_sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('origin_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='core.origincountry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='cars.car')),
            ],
        ),
    ]
