# Generated by Django 6.0.3 on 2026-05-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('hybrid', 'Hybrid'), ('diesel', 'Diesel'), ('electric', 'Electric')], default=2, max_length=50),
            preserve_default=False,
        ),
    ]
