# Generated by Django 6.0.3 on 2026-06-09 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_fuel'),
        ('core', '0003_alter_origincountry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='origin_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='core.origincountry'),
        ),
    ]
