# Generated by Django 6.0.3 on 2026-06-12 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_origin_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-is_available', 'is_reserved', 'is_sold', '-created_at']},
        ),
    ]
