# Generated by Django 6.0.3 on 2026-05-17 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_import_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_import_days', models.PositiveIntegerField()),
                ('required_documents', models.TextField()),
                ('customs_fees', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('supplier_purchase', 'Supplier Purchase'), ('documents_preparation', 'documents in preparation'), ('international_shipping', 'International Shipping'), ('malaysia_customs', 'Malaysian Customs'), ('local_delivery', 'Local Delivery'), ('delivered', 'Delivered')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_info', to='cars.car')),
            ],
        ),
    ]
