# Generated by Django 6.0.3 on 2026-06-06 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_fuel'),
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importinfo',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_info', to='cars.car'),
        ),
        migrations.AlterField(
            model_name='importinfo',
            name='estimated_import_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='importinfo',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('supplier_purchase', 'Achat fournisseur'), ('documents_preparation', 'Documents en préparation'), ('international_shipping', 'Expédition internationale'), ('malaysia_customs', 'Douane Malaisie'), ('local_delivery', 'Livraison locale'), ('delivered', 'Livré')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='importinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
