# Generated by Django 6.0.3 on 2026-06-12 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Facture'), ('contract', 'Contrat'), ('passport', 'Passeport'), ('id_card', 'Carte identité'), ('customs', 'Document douanier'), ('registration', 'Immatriculation'), ('vehicle_photo', 'Photo véhicule'), ('other', 'Autre')], max_length=50)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_by_admin', models.BooleanField(default=False)),
                ('is_validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orders.order')),
            ],
        ),
    ]
