# Generated by Django 6.0.3 on 2026-06-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_validated_at_document_validated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_validated',
        ),
        migrations.AddField(
            model_name='document',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=20),
        ),
    ]
