# Generated by Django 6.0.3 on 2026-06-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(choices=[('deposit_20', 'Acompte 20%'), ('remaining', 'Restant 80%'), ('full', 'Paiement total')], max_length=20),
        ),
    ]
