# Generated by Django 6.0.3 on 2026-06-09 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_origincountry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportCostRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_shipping_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customs_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('insurance_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('processing_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_days', models.PositiveIntegerField(default=45)),
                ('is_active', models.BooleanField(default=True)),
                ('origin_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_cost_rules', to='core.origincountry')),
            ],
        ),
    ]
