# Generated by Django 6.0.3 on 2026-06-09 16:40

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=django_countries.fields.CountryField(default=3, max_length=2),
            preserve_default=False,
        ),
    ]
