# Generated by Django 6.0.3 on 2026-06-09 17:02

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='origincountry',
            name='country',
            field=django_countries.fields.CountryField(default=4, max_length=2),
            preserve_default=False,
        ),
    ]
