# Generated by Django 6.0.3 on 2026-06-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_origincountry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='origincountry',
            options={'verbose_name': "Pays d'origine", 'verbose_name_plural': "Pays d'origine"},
        ),
        migrations.RenameField(
            model_name='origincountry',
            old_name='is_activate',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='origincountry',
            name='code',
        ),
        migrations.RemoveField(
            model_name='origincountry',
            name='name',
        ),
    ]
